[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm install', 'cd client && npm install']

[phases.build]
cmds = ['cd client && npm run build']

[start]
cmd = 'NODE_ENV=production node server/index.js'

