[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm ci --production=false', 'cd client && npm ci --production=false']

[phases.build]
cmds = ['cd client && npm run build']

[start]
cmd = 'node server/index.js'

